### ISSUE TITLE
Theming: content types

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#179]
Ready for site freeze when a range nodes of each type have been created and approved
- [x] add page margins for smallest screens
- [x] Images: responsive images and publication images need configuring 
- [x] resolve width issues with prose
- [x] Create related content

**Article**

**Blog**
- [x] review how to display related project

**Event**
- [x] #127 
- [x] Left column sometimes too long e.g. https://pubs-dev.ac.iied.org/nature-based-solutions-for-climate-change-global-ambition-local-action, https://pubs-dev.ac.iied.org/development-climate-days-2021

**Long read** 
- [x] add remaining components 

**News**
 - [x] News pages display contact at the bottom - like author information on a blog. new block added
 - [x] Also needs a block if new type = press release then show block/ News type press add Press contact block 
 - [x] Add collection
 
**Page**

**Project**
- [x] Create related content to and from 
- [x] Update styling to move contact and project label 
- [x] adjust number pubs showing (should show 12 + show more)

**Publication**
See pubs issue #162 

 -[x] Add content layout paragraphs with sections to other content types. all other types: Section paragraphs to blogs, projects, news, articles, event. Note: to be done at later stage

**Comment by ncktrnr** [comment]
Blogs issue where author name repeated in blogger info field. Check with Matt

**Comment by cbrody** [comment]
@ncktrnr @mattjobob is now taggable!

**Comment by cbrody** [comment]
@ncktrnr would this issue be a good place to list the content types that still need theming, e.g. News/Press releases? The relevant migration #133 seems successful.

**Comment by ncktrnr** [comment]
There are templates for each content type, but still some adjustments needed for each. I've update the comments above.

**Comment by cbrody** [comment]
There's an issue with the linked pubs in Projects not displaying the correct (or sometimes any ) image: see Projects tab int eh [Testing spreadsheet](https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=635051503) for some examples.

**Comment by cbrody** [comment]
Long reads: the Copy link and Print/PDF buttons don't work yet.
