### ISSUE TITLE
Theming: taxonomy terms

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#196]
Ready for site freeze when a range terms from each vocabulary have been created and approved
- [x] Add pagination: view more/scroll, various, pager style update if using. for themes all, tags all, collection publications
- [x] refine options for themes, create view
- [x] people need to link to groups (taxonomy)
- [x] #222
- [x] #220 
- [x] Add menus
- [x] check spacing between sections

**Theme**
- [x] Added view Publication slider (Content) this works with CSS only. JS needs adding #222
- [x] Add tags to themes 
- [x] Decide on pagination, view more or infinite scroll behaviour
- [x] Add pubs slider when ready
- [x] Link view more <theme> publications on pubs slider

**Collection**

- [x] field for collection badge
- [x] field for collection short description/link text (accompanies badge)\
- [x] function for type of collection
- [x] add tags and themes to collections (twig update needed to display)
- [x] tags need displaying via layout builder?
- [x] Theme and add JS to tabs layout section 
- [x] Add language switcher 

**Tag**

- [x] Add node count?

**Person / profile** (now separate task)

- [x] Add Twig and views for Organisation, Series, List

**Comment by ncktrnr** [comment]
Layout added for tabbed section, twig needs updating to add tab function.

**Comment by cbrody** [comment]
@ncktrnr the collection cards aren't displaying as a stack and the "Collection" label is missing following the latest update - perhaps some config was changed on stage that hasn't been captured (see `/urban` for an example. Also Event cards such as the CBA16 one on `/climate-change` are showing the node created date instead of event date.

**Comment by cbrody** [comment]
@ncktrnr Branch https://github.com/IIED-org/IIED-main/tree/feature/196-collection-pages has updated [taxonomy-term--collection.html.twig](https://github.com/IIED-org/IIED-main/compare/feature/196-collection-pages?expand=1#diff-3a782a6f2f6ebbf0dc906340e6978dfd6e20e6ad2692eccce78babebfe8b8154) to display themes & language switcher on Collection term pages. Needs some work - see the TODO for info)

![Image](https://user-images.githubusercontent.com/511131/183727975-21b6d170-75ca-4dbd-b45e-08ab60de36af.png)
![Image](https://user-images.githubusercontent.com/511131/183727974-1124d355-39ef-4b1b-8397-20f29b1c4d09.png)

**Comment by cbrody** [comment]
Latest commit now has linked themes & language switcher in (more or less ) the right place. Wasn't sure about Tags display.
