### ISSUE TITLE
Component for accordion paragraph

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/IIED-main#204]
Hi @ncktrnr and @cbrody 

We discussed creating a paragraph for an accordion, with appropriate fields and javascript to render the accordion. 

A quick search took me to this: 

https://codepen.io/QJan84/pen/zYvRMMw

But the official docs for components appears to be behind a paywall:

https://alpinejs.dev/component/accordion

Do you have an account with them?

@ncktrnr - do you have a preferred approach to the accordion?

Test page: https://iied-main-stage.ac.iied.org/test-page-accordion

**Comment by ncktrnr** [comment]
There are a few potentially useful sources I've been looking at: https://www.hyperjs.dev/ and https://www.alpinetoolbox.com/examples/ have example accordions using Alpine JS. Style-wise I was thinking something close to this https://tailwindcomponents.com/component/tailwind-css-accordion

**Comment by finnlewis** [comment]
@ncktrnr will merge the paragraph into dev-master then let me know!

**Comment by ncktrnr** [comment]
Hi @finnlewis 

Update: there is a new paragraph type on the main branch called Accordion box. No fields have been added yet. We discussed a possible field pair – title and body – for each section of content. We also discussed whether we need an option to change the heading tag, on reflection I think it’s fine for them all to be H3.

I was looking at this version as a starting point for Alpine JS https://www.hyperjs.dev/examples/accordion, the version with smoother animation might be a nice to have https://www.hyperjs.dev/examples/accordion-with-plugin 
Further examples here https://www.alpinetoolbox.com/examples/

I prefer accordions where the collapsed state is default with all content panels closed; and where users can independently open each section allowing more than one to be open at once. The alternative has the first item open by default and only one section may be open at once (example: https://tailwindcomponents.com/component/tailwind-css-accordion)

**Comment by ncktrnr** [comment]
Here’s some suggested HTML, example content and Tailwind classes. 
The icons to indicate open or closed are all from https://heroicons.com/ (outline versions)

` 
      <div class="bg-white border border-gray-300 rounded-xl">
        <div id="accordion-collapse" data-accordion="collapse">
          <h3 id="accordion-collapse-heading-1">
            <button
              type="button"
              class="flex items-center justify-between w-full p-5 text-xl text-left"
            >
              <span
                >Where does Africa fit in the Belt and Road Initiative?</span
              >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="flex-shrink-0 w-6 h-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M5 15l7-7 7 7"
                />
              </svg>
            </button>
          </h3>
          <div
            id="accordion-collapse-body-1"
            aria-labelledby="accordion-collapse-heading-1"
          >
            <div class="p-5 border-b border-gray-300">
              <p>
                Where does Africa fit in the Belt and Road Initiative? A
                trillion dollars, more than 70% of the world’s population, and
                huge ambition are woven together in China’s Belt and Road
                Initiative (BRI). Called ‘one belt, one road’ in Chinese, it’s a
                revival of China’s ancient transcontinental land and sea silk
                roads. But there is little nostalgia in BRI.
              </p>
            </div>
          </div>
          <h3 id="accordion-collapse-heading-2">
            <button
              type="button"
              class="flex items-center justify-between w-full p-5 text-xl text-left border-b border-gray-300"
            >
              <span>Collapse heading 2</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="flex-shrink-0 w-6 h-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M19 9l-7 7-7-7"
                />
              </svg>
            </button>
          </h3>
          <div
            id="accordion-collapse-body-2"
            class="hidden"
            aria-labelledby="accordion-collapse-heading-2"
          >
            <div class="p-5 border-b border-gray-300">
              <p>more text</p>
              <p>More text</p>
            </div>
          </div>
          <h3 id="accordion-collapse-heading-3">
            <button
              type="button"
              class="flex items-center justify-between w-full p-5 text-xl text-left"
            >
              <span>Collapse heading 3</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="flex-shrink-0 w-6 h-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M19 9l-7 7-7-7"
                />
              </svg>
            </button>
          </h3>
          <div
            id="accordion-collapse-body-3"
            class="hidden"
            aria-labelledby="accordion-collapse-heading-3"
          >
            <div class="p-5">
              <p>More text</p>
            </div>
          </div>
        </div>
      </div>`

**Comment by finnlewis** [comment]
Hi @ncktrnr 

I've got the basics of an alpine based accordion woking on 

But I'm having trouble with the Tailwind classes - I'd love to add a bit of padding, but classes like px-5 don't seem to have any effect. I'm looking here for reference: https://tailwindcss.com/docs/padding 

Looks like this at the moment

![image](https://user-images.githubusercontent.com/326588/184409488-46f4dbbf-bdff-42f6-ba43-6ec8de120dfd.png)

Then clicking the middle heading: 

![image](https://user-images.githubusercontent.com/326588/184409546-c5ba3c65-f3a5-435b-a29b-fab60d323226.png)

Couple of other things I'd like to address: 

- transition smoothing, not yet working, I was trying to make it work like this one: https://www.hyperjs.dev/components/accordion-singular
- rotating the svg arrow icon. In the example, it uses Alpine to swap out classes for rotate-180, but these classes seem to have no effect on any element I'm trying them with. 

I think my lack of experience with Tailwind is showing here, any pointers?

We have a call in the calendar Monday morning, so perhaps we can run through a few of these issues together and come to a rapid resolution then.

If you have any suggestions in the mean time, I might be working on Sunday too.

Many thanks!

**Comment by finnlewis** [comment]
Here's a pull request to review the changes so far: 
https://github.com/IIED-org/IIED-main/pull/371

**Comment by finnlewis** [comment]
Over to you to review @ncktrnr 

I tidied up the css a bit, but you might want to sprinkle some of your magic: 



![Image](https://user-images.githubusercontent.com/326588/184644690-bf65fe0c-d2fc-4c62-a1b4-63d6dacc2f35.png)

**Comment by mattjobob** [comment]
Looks good!
