### ISSUE TITLE
Component for tab paragraph

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#211]
Box with tabs to allow navigation between groups of content. 

There is a paragraph type called Tab box. It’s not in use yet and no fields have been added. Much like the accordion it may be best suited to a field pair – title and body – for each group of content. 

This was the reference I was using for Alpine JS, again only as a starting point if there’s a better approach
https://www.hyperjs.dev/examples/tabs

I mentioned we also need some tabs within term pages using layout builder. Hoping we can use similar functionality, but probably needs some further discussion on how best to implement.

**Comment by ncktrnr** [comment]
Here’s some suggested HTML and Tailwind classes below as a starting point. There’s three versions. I created the tabs as a list, then realised it might be easier to create if they were separate buttons. Version 3 starts with flex-col for small screens. Typically there will only be 2-3 tabs, but there's no fixed limit so this might be the most flexible option.

`      <div class="p-4 mb-8 border border-gray-300 prose-base rounded-xl">
        
        
        <div class="flex border-b border-gray-300">
          <button
            class="h-10 px-4 py-2 -mb-px font-semibold text-center text-gray-900 bg-transparent border-b-2 hover:text-gray-900 border-iiedblue-500 whitespace-nowrap focus:outline-none"
          >
            Tab one
          </button>

          <button
            class="h-10 px-4 py-2 -mb-px font-semibold text-center text-gray-500 bg-transparent border-b-2 border-transparent hover:text-gray-900 whitespace-nowrap cursor-base focus:outline-none"
          >
            Tab two
          </button>

          <button
            class="h-10 px-4 py-2 -mb-px font-semibold text-center text-gray-500 bg-transparent border-b-2 border-transparent hover:text-gray-900 whitespace-nowrap cursor-base focus:outline-none"
          >
            Tab three
          </button>
        </div>

        
        <div class="border-b border-gray-300">
          <ul class="flex -mb-px">
            <li class="mb-0 mr-2">
              <a
                href="#"
                class="inline-block px-4 py-2 font-semibold text-center text-gray-500 border-b-2 border-transparent rounded-t-lg hover:text-gray-900 hover:no-underline"
                >Tab one</a
              >
            </li>
            <li class="mb-0 mr-2">
              <a
                href="#"
                class="inline-block px-4 py-2 font-semibold text-center text-gray-900 border-b-2 rounded-t-lg hover:text-gray-900 border-iiedblue-600 hover:no-underline active"
                aria-current="page"
                >Tab two</a
              >
            </li>
            <li class="mb-0 mr-2">
              <a
                href="#"
                class="inline-block px-4 py-2 font-semibold text-center text-gray-500 border-b-2 border-transparent rounded-t-lg hover:text-gray-900 hover:no-underline"
                >Tab three</a
              >
            </li>
            <li class="mb-0 mr-2">
              <a
                href="#"
                class="inline-block px-4 py-2 font-semibold text-center text-gray-500 border-b-2 border-transparent rounded-t-lg hover:text-gray-900 hover:no-underline"
                >Tab four</a
              >
            </li>
          </ul>
        </div>

        
        <div>
          <nav class="flex flex-col border-b border-gray-300 sm:flex-row">
            <button
              class="block px-6 py-2 font-semibold text-gray-700 border-b-2 border-iiedblue-500 hover:text-gray-900 focus:outline-none"
            >
              Tab 1</button
            ><button
              class="block px-6 py-2 font-semibold text-gray-700 hover:text-gray-900 focus:outline-none"
            >
              Tab 2</button
            ><button
              class="block px-6 py-2 font-semibold text-gray-700 hover:text-gray-900 focus:outline-none"
            >
              Tab 3</button
            ><button
              class="block px-6 py-2 font-semibold text-gray-700 hover:text-gray-900 focus:outline-none"
            >
              Tab 4
            </button>
          </nav>
        </div>
      </div>`

**Comment by finnlewis** [comment]
Hey @ncktrnr 

I've made a first pass at this.

See https://github.com/IIED-org/pubs/pull/295

Here's how it looks locally: 

![image](https://user-images.githubusercontent.com/326588/176225901-5a5d488a-9036-4cdb-88cc-6de395037744.png)

Up for discussion on whether there is a better approach to the hook_preproces for the paragraph to wrangle some arrays for ease of use or if there is a way that can be done with twig magic, but the approach seems to work at least.

Let me know if you'd like to discuss it on a quick call at some point. 

Cheers,

Finn

**Comment by ncktrnr** [comment]
Thanks, that’s great. Keen to take a look, but may as well wait until Chris is about too. How about some time Wednesday morning?

**Comment by mattjobob** [comment]
Looks great
