### ISSUE TITLE
Component for Highcharts paragraph

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#213]
The data series and JS links are presently all within the page, so we need a better way to implement. 

There’s presently a paragraph type called Media embed with a basic text field. Probably best to create a new paragraph type exclusively for Highcharts rather than repurpose?

There are a few different types of chart (see https://www.highcharts.com/demo ), so the JS library links are not always the same.
There are a few standard elements like IIED colours included within the series options. 

Examples
https://www.iied.org/supporting-more-equal-numbers-international-climate-debates
https://www.iied.org/continuity-change-worlds-20-largest-cities
https://www.iied.org/worlds-100-largest-cities-1800-2020-beyond
https://www.iied.org/qa-blog-series-explores-transition-predominantly-urban-world

**Comment by finnlewis** [comment]
@ncktrnr could you link to an example where there are two charts on a page?

**Comment by ncktrnr** [comment]
Examples with multiple charts: 
https://www.iied.org/worlds-100-largest-cities-1800-2020-beyond
https://www.iied.org/continuity-change-worlds-20-largest-cities

**Comment by finnlewis** [comment]
@ncktrnr and @cbrody and @mattjobob 

Could you list the charts we need to present in order of priority? It strikes me that 'll need to take each type of chart one at a time, so best to do the highest priority first.

**Comment by finnlewis** [comment]
OK - I'll create a new paragraph type 'highchart' and attach the highcharts library and accessibility js librbary.
Then I'll start to break out the parameters, title, type, colours etc. 
Perhaps a multi-value text field for data series?

**Comment by finnlewis** [comment]
Looking quite good locally: 

![image](https://user-images.githubusercontent.com/326588/184670058-e2632777-fd5c-4656-9b3b-b4655284713d.png)

**Comment by finnlewis** [comment]
I've gone with this module: https://www.drupal.org/project/charts

Seems to work well. I've created a 'highchart' paragraph and added the chart field to it. Successfully added two charts to the same page, and with a little fiddling, you can get them looking much like those on the D7 site.

Here's an idea of the form you can use to add the data: 

![image](https://user-images.githubusercontent.com/326588/184670415-e048718c-e670-4baa-8ca5-c3f4760786db.png)

I figure this will get us 90% there. If there are specific configuration parameters that are not yet available, let's extend the module.

Here's a pull request for review: https://github.com/IIED-org/IIED-main/pull/374

**Comment by finnlewis** [comment]
@cbrody @ncktrnr let me know what you think... is this enough for now or do we need more power?

**Comment by cbrody** [comment]
@finnlewis this looks great at first glance, thanks!

**Comment by finnlewis** [comment]
I can't work out how to control fonts using the api hooks. The hooks fire, but I don't think HighCharts specific configuration is being passed to the javaScrpit library.

If we do want to extend the options and get it working, probably best to test the patch on this issue and work there with others in the community to build and test: https://www.drupal.org/project/charts/issues/3046981

**Comment by mattjobob** [comment]
Agree this is fine for our needs now, and we can work with the commuinity to develop as needed in the future.
