### ISSUE TITLE
Config: Language function

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#218]
- [x] Configure and test i18n functionality
- [x] Configure content types with translatable fields
- [x] News
- [x] Blog
- [x] Article
- [x] Project
- [x] Event
- [x] Long read
- [x] Collection (e.g. GWI)
- [x] Paragraphs (some)

- [x] Add toggle 
- [x] Test
- [x] check URLs revert to correct language e.g. default English if you follow a project link from here /pt-br/20876iied

OK for pubs nodes to follow a different pattern

**Comment by cbrody** [comment]
How do we want the toggle to work? Is the language switcher on publication nodes different from on other content?

**Comment by cbrody** [comment]
OK to have switcher in different locations for now, use comma-separated list of languages

**Comment by cbrody** [comment]
Language switcher is now in place for Blogs, News, Articles, Projects, Long reads.

**Comment by cbrody** [comment]
Moved language toggle to top right. All taxonomy vocabularies have been set to translatable to enable content_translation_redirect to work correctly. #360 #361

**Comment by mattjobob** [comment]
Good job
