### ISSUE TITLE
Config: images

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#219]
Creating and configuring responsive image styles and functionality

- [x] review how pubs images are generated
- [x] #246 
- [x] Set up all responsive styles 
- [x] optimise images
- [x] Add paragraphs image fields as required (needs review)

Image sizes listed on Content to create or recreate https://docs.google.com/spreadsheets/d/18BP4VQSlkh6KVbRybrqoJmBZ3q6TA41kzjOALGYsOJs/edit#gid=2114246431

**Comment by cbrody** [comment]
@ncktrnr some body field images are missing captions (class="caption" filter) - do we need to replicate this functionality? See row 12 here: https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=0

**Comment by cbrody** [comment]
> @ncktrnr some body field images are missing captions (class="caption" filter) - do we need to replicate this functionality? See row 12 here: https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=0

Probably don't need this as caption / title text appears in on hover.

**Comment by mattjobob** [comment]
No need to address above as legacy content
