### ISSUE TITLE
Content: custom pages

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#231]
As per [Content to create](https://docs.google.com/spreadsheets/d/18BP4VQSlkh6KVbRybrqoJmBZ3q6TA41kzjOALGYsOJs/edit#gid=1709556247) **Odds and ends** and **Page** tabs

**Comment by mattjobob** [comment]
- [ ] Pages
- [ ] Newsletters
- [ ] Odds and ends

**Comment by mattjobob** [comment]
Almost done. Few final bits to do on pages and odds and ends to sort outstanding issues, ie subject access request form not working.

**Comment by ncktrnr** [comment]
I've looked at the subject access request form and it seems like Click D is not much good for longer form fields. Do you think we can replace the form with a request to email for now? It has never had any submissions.

**Comment by mattjobob** [comment]
I'm less concerned about that the field length than the fact it's not working. Which might be why there's been no submissions! (although you'd have thought we'd have had complaints if so). 

I'll liaise with Catherine on it regardless, but it would be good to know why it isn't working if it's obvious.

**Comment by ncktrnr** [comment]
That's done, so I've checked it off
