### ISSUE TITLE
Admin: UI

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#233]
Design/build/test/iterate editor's UI, add and clean up admin views

**Manager (and editor?)** 
- [x] Update Maintenance view. delete unused pages and ensure all on one set of tabs
- [x] Update Maintenance view to create view of all publications for reporting. Already there, but needs checking
- [x] create table of recently added/changed content to appear on login (currently no redirect for managers)

**Publications editor** 
- [x] update login screen (modal?) 
- [x] redirect after login to new dashboard
- [x] create view of all tags to add to publications (admin/edit) dashboard
- [x] Permanent link (menu item?) to admin/edit page (use shortcuts?)

**Other**
- [x] create view of all tags (this is a public list and could be by XML) *urgent*
- [x] Add Views as necessary
- [x] Clean up outdated Views

- [x] add container class for admin screens. Could be added to page.html.twig
- [x] Configure layout builder restrictions per vocabulary / [Clean up layout builder](https://www.drupal.org/project/layout_builder_restrictions) 
- [x] Clone Content view and configure to create a dashboard for content editors --or-- redirect logged in users to existing content view (preferred option, see module below)
- [x] configure Layout builder restrictions
- [x] Add GIN theme (#181) 
- [x] Define pages to include, add and configure [admin_theme](https://www.drupal.org/project/admin_theme) Prioritise for publications users

Redirect after login: 
https://www.drupal.org/project/redirect_after_login
Possible use: https://www.drupal.org/project/fancy_login
Preferred use: https://www.drupal.org/project/gin_login 

Useful article on customising layout builder https://www.droptica.com/blog/layout-builder-customization-creating-custom-layout-drupal/

**Comment by ncktrnr** [comment]
gin_lb looks good, but the toolbar is not currently visible

**Comment by cbrody** [comment]
https://github.com/IIED-org/IIED-main/tree/feature/337-user-roles has two new Dashboard (/admin/edit) views, not yet merged though.

**Comment by cbrody** [comment]
This needs testing (and documenting!) You can download all tags as a CSV file using the link at the bottom of the [popular tags view](https://www.iied.org/admin/popular-tags) or view them as HTML at https://www.iied.org/admin/all-tags

**Comment by cbrody** [comment]
For anonymous users the [all-tags](https://www.iied.org/admin/all-tags) page displays the tags in a horizontally scrolling section at the top - would you be able to look at this @ncktrnr ?

**Comment by cbrody** [comment]
@mattjobob you can share this link for direct access to the tags CSV file@: https://www.iied.org/admin/popular-tags?page&_format=csv

**Comment by mattjobob** [comment]
List of views created for paertners work in case useful here:

Publications https://iied.org/admin/reporting/partner
Projects https://iied.org/admin/reporting/partner/projects
Blogs https://iied.org/admin/reporting/partner/blogs
Auth/org publications https://iied.org/admin/reporting/partner/publications-special
Organisations https://iied.org/admin/reporting/partner/organisations
Authors https://iied.org/admin/reporting/partner/authors
