### ISSUE TITLE
Content: Translations

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#235]
Recreate translated content on new site

- [x] #218 
- [x] Add items to Translations tab on [Content to create](https://docs.google.com/spreadsheets/d/18BP4VQSlkh6KVbRybrqoJmBZ3q6TA41kzjOALGYsOJs/edit#gid=1092492315)
- [x] Recreate content on new site
- [x] Test

**Comment by cbrody** [comment]
Hi @A-McGill and @mattjobob, recently entered translations are showing at the top of the search results when sorting by date, e.g. https://iied-main-stage.ac.iied.org/search?k=climate%20change&sort=field_sort_date&order=desc  

This is because the node created date is a translatable field and needs to be set to the original date that the item was published.

**Comment by mattjobob** [comment]
Georgina has been through all translated content and checked/amended dates to tally with publish dates. I have tested
