### ISSUE TITLE
Component: banners

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#241]
Add a custom block that can be used to create banners on term pages
Will only be used on terms 
Has title, description, link and optional images 
Option to change the background colour
Option to change link style

**Comment by mattjobob** [comment]
Have experimented with this and looks god.

How do you change the background colour? Do you mean by putting the section as grey?

**Comment by ncktrnr** [comment]
Yes, grey only at the moment. Other colours and styles can be added...

**Comment by mattjobob** [comment]
Sorry, one more question...  It seems banners always have to link to a page on the site. This is good, but I can envisage scenarios where we'd want to link out elsewhere. Is this feasible/practical?

**Comment by ncktrnr** [comment]
I was thinking for now we use the custom banner blocks to accommodate anything non-standard. With the intention that over time additional styles we like get added to design system components and we create new banner blocks specifically for those styles.
