### ISSUE TITLE
Component: copy and print

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#257]
Buttons provided for copy page link and print this page. Function needs adding to templates
Could be split into two partials

Possibly useful:

Copy to clipboard 
https://github.com/ryangjchandler/alpine-clipboard
https://codepen.io/KevinBatdorf/pen/wvMNebe

Print page 
https://devdojo.com/mithicher/print-component-with-laravel-blade-and-alpinejs

**Comment by cbrody** [comment]
I've done this very simply with plain JS in #384.

**Comment by cbrody** [comment]
Do we need to review the print styles?

**Comment by mattjobob** [comment]
@cbrody This looks good on all content types except blogs, eg https://iied-main-stage.ac.iied.org/three-asks-strengthen-locally-led-action-new-biodiversity-finance

On blogs, the 'copy' button/icon is missing and the print/pdf doesn't work

**Comment by mattjobob** [comment]
Thanks @cbrody. All good.

Copy button now added and working; print/pdf button working; IIED blog and CC information on separate line underneath
