### ISSUE TITLE
Component: timeline

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#261]
Add paragraph type and template styling for timeline

**Comment by mattjobob** [comment]
This looks good.

Depending on the length of the date, the date is obscured by the timeline text - eg see top of timeline on https://iied-main-stage.ac.iied.org/test-page-accordion @ncktrnr 

Is there a way to insert a photo? (other than in-line?)

**Comment by ncktrnr** [comment]
Works best when added to one column wide section, which should fix the spacing issues. For now photos are only with in the text.
