### ISSUE TITLE
Component: logo block

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#263]
Paragraph type with entity reference to organisation. Can be used to create a grid display of sponsor logos

**Comment by mattjobob** [comment]
Looks good.

Does the spacing on mobile/two abreast need adjusting at all? Quite a large gap between logos eg https://iied-main-stage.ac.iied.org/test-blog @ncktrnr

**Comment by ncktrnr** [comment]
Well spotted, that's now fixed
