### ISSUE TITLE
Content: create terms

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#265]
Includes people, organisations, collections (such as GWI)

Some clean up needed, e.g. entries with no first/last name e.g. /people/irish-aid and /people/dc-days 
Merge terms like https://pubs.iied.org/author/achala-chandani-abeysinghe /people/achala-c-abeysinghe

- [ ] decide what heading are required: create labelling system and apply to themes etc.

**Comment by ncktrnr** [comment]
Closing as duplicate
