### ISSUE TITLE
Theming: Cookie warning

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#267]
Update text and styling on cookie warning

**Comment by ncktrnr** [comment]
Minor adjustments done. OK for now, but longer term would be good to do some custom styling to match site theme. 
I think the text could do with an update.

**Comment by mattjobob** [comment]
Can we update text slightly please:

This website collects cookies so we can improve the site and provide you with a better user experience. By clicking on any link on our site, you give your consent to this.

**Comment by mattjobob** [comment]
Change to: @ncktrnr 

We use cookies to improve the site and provide you with a better experience. Click OK or any link to give your consent.

**Comment by ncktrnr** [comment]
Updated.
