### ISSUE TITLE
Site testing: Compatibility

### ISSUE THREAD

**Issue by DavidIIED** [IIED-org/IIED-main#273]
Ensure that the web application displays correctly across different devices. 

**Browser Compatibility Test:** 

- Web application is being displayed correctly across browsers
- JavaScript, AJAX and authentication is working fine
- Mobile Browser Compatibility

**Operating System compatibility:**

- Web elements like buttons, text fields etc. display correctly
- Various combination of Operating systems such as Windows, Linux, Mac, and Browsers such as Firefox, Internet Explorer, Safari etc.

Methods: 
Automatic - https://www.browserstack.com/live
Manual - Test on Windows, Mac and Linux PCs

- [x] Review and update accordingly

**Comment by cbrody** [comment]
See[ Device/browser tab on testing sheet](https://docs.google.com/spreadsheets/d/1ZHjl2YQQw0S-KOG8RcSGRHypujkIylyjssW3-H7fG2I/edit#gid=586276370 ):
