### ISSUE TITLE
Site testing: Performance

### ISSUE THREAD

**Issue by DavidIIED** [IIED-org/IIED-main#274]
Ensure the site works under all loads. 

- Caching configuration optimised
- Images optimised and responsive
- Test website response times at different connection speeds
- Load test the web application to determine its behavior under normal and peak loads
- Stress test the web site to determine its break point when pushed to beyond normal loads at peak time
- Test if a crash occurs due to peak load, how does the site recover from such an event
- Make sure optimization techniques like gzip compression, browser and server side cache enabled to reduce load times

**Methods:**
Drupal/Acuia site admin options
https://www.thinkwithgoogle.com/intl/en-gb/feature/testmysite/
https://www.webpagetest.org/
https://search.google.com/search-console

**Comment by cbrody** [comment]
Initial report: [202200824 home page lighthouse.pdf](https://github.com/IIED-org/IIED-main/files/9415816/202200824.home.page.lighthouse.pdf)

**Comment by cbrody** [comment]
[20220930 home page lighthouse.pdf](https://github.com/IIED-org/IIED-main/files/9684173/20220930.home.page.lighthouse.pdf)

**Comment by cbrody** [comment]
- [ ] Look at https://www.drupal.org/project/purge_file for when PDFs are replaced

**Comment by mattjobob** [comment]
Is this completed?

Should https://www.drupal.org/project/purge_file assessment be added to another issue?

Should we store the Lighthouse reports in Teams as well?

**Comment by cbrody** [comment]
Yes to both questions. I've created issue #530 and will post Lighthouse reports in the IIED-main channel.

**Comment by cbrody** [comment]
There's more optimisation (particularly of images) that could be implemented, but shall we close this for now @DavidIIED?

**Comment by mattjobob** [comment]
@DavidIIED - see Chris' Q above

**Comment by DavidIIED** [comment]
Yes, happy tp close this.
