### ISSUE TITLE
SEO tasks

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#299]
Adding a new issue as I'm not sure if all of this is covered

- [x] Add configure Metatag module
- [x] Add/enable XML sitemap 
- [x] Configure xmlsitemap
- [x] Set up Search 404
- [ ] Review any useful modules, e.g. https://www.drupal.org/project/seo_checklist, https://www.drupal.org/project/yoast_seo 
- [x] review robots.txt (do we still hide tags?) / update robots.txt
- [x] config rabbit hole for terms not shown like staff, guest etc. 
- [x] config pathauto settings for all content types and terms
- [x] Additional and replacement redirects / check redirects, see spreadsheet. Important redirects like /jobs need adding https://docs.google.com/spreadsheets/d/1NTbnHFZDLOkhvxlUUdvVSaplt0rKx97v1XXr_j2GSkA/edit#gid=1247948384
- [x] There's an [issue with search404 not showing a message](https://www.drupal.org/project/search404/issues/3291141) e.g. "Page not found, doing a search instead..." to anonymous users.
- [x] Check htaccess redirects

Add documentation here https://docs.google.com/document/d/1nAYxwl0jhPo6bpSuSSEcMx4nSJ1e6XLXAa_LmVB8s2E/edit#

**Comment by ncktrnr** [comment]
Search 404 enabled, but not currently working

**Comment by cbrody** [comment]
> Search 404 enabled, but not currently working

Module patched and now working OK.

**Comment by cbrody** [comment]
There's an [issue with search404 not showing a message](https://www.drupal.org/project/search404/issues/3291141) e.g. "Page not found, doing a search  instead..." to anonymous users.

**Comment by cbrody** [comment]
xmlsitemap added and enabled, .htaccess redirects updated in #443, also updated php to v8.1 in .lando.yml so a rebuild is necessary.

**Comment by mattjobob** [comment]
Have tested tweeting some pages, but not appearinfg as I'd expect. See screengrabs from when you post links with the current site and new site

![Image](https://user-images.githubusercontent.com/103056527/193245607-08c53374-949a-4ba0-bfe0-b937f7da0cff.JPG)
![Image](https://user-images.githubusercontent.com/103056527/193245608-c3ad0145-40b3-4d65-ae40-cdfb230ad3e6.JPG)

](url)

**Comment by cbrody** [comment]
Twitter images now fixed - can you test @mattjobob

**Comment by mattjobob** [comment]
No difference, I'm afraid. Is it an issue because it's a staging site?

**Comment by cbrody** [comment]
Pubs won't currently show images but other types should now...

**Comment by mattjobob** [comment]
Still no change

**Comment by cbrody** [comment]
Can this be closed now?

**Comment by mattjobob** [comment]
Yes, all now working.
