### ISSUE TITLE
Fix missing files/images from migration

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#328]
From the log:
Rewrite inline image styles: Cannot find reference to biodiversity-news_1.png from node .
Rewrite inline image styles: Cannot find reference to pictures/picture-717-1365766523.jpg from node 19256.
Rewrite inline image styles: Cannot find reference to pictures/picture-5671-1534345661.jpg from node 23596.
Rewrite inline image styles: Cannot find reference to pictures/picture-66-1334666115.jpg from node 24276.
Rewrite inline image styles: Cannot find reference to pictures/picture-6526-1550233050.jpg from node 28246.
Rewrite inline image styles: Cannot find reference to pictures/picture-6526-1550233050.jpg from node 28496.
Rewrite inline image styles: Cannot find reference to pictures/picture-6526-1550233050.jpg from node 28551.
Rewrite inline image styles: Cannot find reference to pictures/picture-10491-1601547645.jpg from node 139931.
Rewrite inline image styles: Cannot find reference to pictures/picture-46-1632907681.jpg from node 139931.

**Comment by mattjobob** [comment]
Have checked/fixed all these
