### ISSUE TITLE
Theming: Person/profile

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#329]
- [x] Fix publications view, causing page to time out ( /admin/structure/views/view/term_publications) in #347
- [x] add Load more to blogs/pubs view?

**Comment by cbrody** [comment]
Added a pager to the term_publications view (currently 16 items per page) due to out of memory errors on `/people/lorenzo-cotula`. @ncktrnr should we look at converting to Load more? Would need relevant template.

**Comment by mattjobob** [comment]
The link to someone's Twitter profile just goes to Twitter, not that specific person's Twitter, eg https://iied-main-stage.ac.iied.org/people/helen-oconnor

Notes: 

Language: English is no longer insterted automatically, you have to put it in at the start
Twitter: the @ symbol is no longer insterted automatically, you have to put it in at the start (this might relate to the above)

**Comment by mattjobob** [comment]
Telephone number: Can you change the automated text that appears to "+44 (0)20 3463 7399" please

**Comment by cbrody** [comment]
> The link to someone's Twitter profile just goes to Twitter, not that specific person's Twitter
Fixed
> Language: English is no longer insterted automatically, you have to put it in at the start
English now set as default
> Twitter: the @ symbol is no longer insterted automatically, you have to put it in at the start (this might relate to the above)
The @ symbol is not needed
> Telephone number: Can you change the automated text that appears to "+44 (0)20 3463 7399" please

All done in #403

**Comment by mattjobob** [comment]
Thanks Chris. All looks good.

One thing we've forgotten on the people page is the video interviews (where available). For some staff, we have a video playlist of their interviews on YouTube. Too late to add (not a problem if so)?

**Comment by mattjobob** [comment]
All now working, thanks
