### ISSUE TITLE
Admin: user roles

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#337]
Roles need correctly setting up and documenting 
Restrict access to config settings
- [ ] restrict access to Manage display layout builder

Viewer
Editor 
Manager 
Administrator 

**Registered user**
Registered users have profile properties, but no further permissions 
Keeping, but no practical use

**Viewer**
Role exists but not used? Can view content they have been invited to view. Statistics, this could be all staff role. 
Embargoed PDFs are viewable with link only.
View all unpublished content
Navigation? NO 
Use case: user needs to check unpublished page 
(look into single use sign in)

**Publications editor**
Same as ed but only for pubs
View all unpublished content
Edit all publications
Edit media
Not lists for now 
Use case: coordinator uploading publication. Create stub publication.

**Editor**
General management and upkeep of a site’s content. Create new entries and edit their own entries. Updates may go through a workflow process, where it’s reviewed by a manager before appearing on the live site.
Edit content. 
Can't create users
Can't edit taxonomy or terms - so not layout builder 
Use case: specific comms staff, dealing smaller ranger of content

**Manager**
More privileges than content editors: create, edit any pages and update status. Can approve content updates submitted by content editors if we set up this workflow. They can directly publish updates to a page without requiring a review by an approver. Can delete pages
Use case: web team, general content management
Add users, control access
Anything that's not config with a few exceptions. 

**Administrator**
Additional config permissions. 
Not for day to day use
All permissions.  

- [x] apply roles to existing users

**Comment by mattjobob** [comment]
Have audited current users, as follows:

**Remove:** 

Matt Fear
Ashan Abeywardena
Ally Renton
Eugenie Galbas
Test manager
Test editor

**Change to just pubs**

Clair Grant-Salmon

**Change to just editor**

Sarah Grainger
Adam Bates
Annette McGill
Jodie Frosdick
Anne Schulthess

**Change to just manager**

Matt Wright
Georgina Diaz
Chris Brody
David Sankar
Nick Turner

**?**

Acquia temp
pubs_admin

**Comment by cbrody** [comment]
Changes from [ #337](https://github.com/IIED-org/IIED-main/tree/feature/337-user-roles) are in PR #460, not yet merged though.

**Comment by cbrody** [comment]
The new roles are now in place but not tested so I haven't made all the changes as requested above. I have converted all existing Editors to Publications editors and blocked the accounts as listed to be removed above but the other changes will need some testing (hence leaving the two Test accounts active).

**Comment by DavidIIED** [comment]
Publications Editors noticed that it was possible to log in this morning! I have blocked them until we are ready...

Test Editor and Test Manager are particularly useful for 'masquerading' to test different roles so please can we keep those permanently?

**Comment by cbrody** [comment]
I've revised the permissions and admin/edit views for the various roles and modified users' roles according to the list [above](https://github.com/IIED-org/IIED-main/issues/337#issuecomment-1265347878). The default shortcut set now has links to common tasks. @mattjobob et al can you let me know if further changes are required?
