### ISSUE TITLE
Content: contact form

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#349]
Contact form needs to be available as a block to place on the term 
Either use sitewide contact or webform
Add Tailwind forms plugin for styling? 

If using site contact form, need this to add it to a block
https://www.drupal.org/project/contact_block

- [x] disable unused forms, including default form
- [x] Update contact information
- [x] theme form 
- [x] test

https://www.drupal.org/docs/8/modules/webform/webform-cookbook/how-to-remove-the-default-contact-form

**Comment by ncktrnr** [comment]
Decision needed

**Comment by cbrody** [comment]
Going with contact_block for now

**Comment by cbrody** [comment]
Enabled in #394

**Comment by mattjobob** [comment]
Have tested
