### ISSUE TITLE
Theming: read more paragraph

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#392]
- [x] issue with close button scrolling all the way to top of page rather than top of read more box
Possible fix: https://stackoverflow.com/questions/25459716/stop-page-scrolling-to-the-top-after-the-user-clicks-a-read-more-link

For example https://iied-main-stage.ac.iied.org/test-blog
https://iied-main-stage.ac.iied.org/biodiversity-loss-more-environmental-emergency
https://iied-main-stage.ac.iied.org/what-makes-sustainable-diet-who-decides-make-change-happen-podcast-episode-5

**Comment by ncktrnr** [comment]
@finnlewis do you have any time to take a look at this issue? Clicking hide takes you to the top of the page at the moment.

**Comment by finnlewis** [comment]
@cbrody is going to check with @mattjobob to confirm if we have additional budget for me to look at this.

**Comment by finnlewis** [comment]
There's this line in the module: 

https://git.drupalcode.org/project/readmore_js/-/blob/2.0.x/js/selector.js#L25

Commenting this out prevents the behaviour.

I've created an issue and can create a patch later to remove it, or better, make it optional.

**Comment by finnlewis** [comment]
Try this https://github.com/IIED-org/IIED-main/commit/e7e405dada53abc8452904b2dd96a2e0de1a2afd

**Comment by cbrody** [comment]
Thanks @finnlewis, with the patch it now scrolls down the page (by a few paragraphs) rather than up.

**Comment by cbrody** [comment]
Closing this as fixed, cheers
