### ISSUE TITLE
Migrate: News items missing field_theme_s_

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#395]
The themes associated with News and Press Release items have not been migrated. Either we need to run an update migration, or the missing themes need to be manually added to the content (480 items).

**Comment by cbrody** [comment]
@finnlewis could you comment on the feasibility of migrating the news and press release content again, with the field_theme_s_ data included?

**Comment by finnlewis** [comment]
@DavidIIED can you confirm if the theme field is actually present on the news content type? I can't see it locally and can't log in to the dev site. Just wanted to check before creating the field and extending the migration.

**Comment by finnlewis** [comment]
Ah yes, sorry, looks like it was added 14 days ago! 
https://github.com/IIED-org/IIED-main/blob/main/config/default/field.field.node.news.field_theme_s_.yml

**Comment by finnlewis** [comment]
Thanks @DavidIIED - this pull request should add the migration config, but we'll need to work out how best to run it and deploy the updates. https://github.com/IIED-org/IIED-main/pull/418

**Comment by finnlewis** [comment]
@DavidIIED if you could confirm here or on Teams or both that I should

a) pull a backup of the database to local
b) run the update migration on the news press and news media migrations
c) push the database back up to dev

**Comment by finnlewis** [comment]
Just to note, we discussed this in Teams and agreed to go ahead: 

**[13:31] finn.lewis (Guest)**
    Hi David Sankar - https://github.com/IIED-org/IIED-main/issues/420 was about importing config to the dev site that had not been imported. This is a relatively safe thing to do and is part of standard deployment practice. My question above and on https://github.com/IIED-org/IIED-main/issues/395 involves overwriting the dev database from my local. 

Specifically: 

a) pull a fresh backup of the dev database to local
b) run the update migration on the news press and news media migrations on my local
c) push the database back up to dev site


This means any edits done to the dev site between my backup and push would be lost. Hence the need to co-ordinate. 


If this is still OK to do, I will do so just after 5pm today. 

**​[13:40] David Sankar**
    Ah, I'd mistakenly conflated the two issues in my mind. Thanks for clarifying. No-one will be making any changes to dev today, so please go ahead as you suggest.

**​[13:46] finn.lewis (Guest)**
    Cool beans, thanks for confirming. I'll do that just after 5pm

**Comment by finnlewis** [comment]
Hi @DavidIIED, @mattjobob @ncktrnr @cbrody 

This is now complete.

For example: http://pubs-dev.ac.iied.org/node/76749/edit now has themes: 

![image](https://user-images.githubusercontent.com/326588/189704895-f0a544f4-bf3a-4ef6-abc9-e14440229c47.png)

I note that the 'updated' timestamp has been amended to the time of migration.

This looks to be a known issue: 
- https://www.drupal.org/project/drupal/issues/3095424

If this is massively inconvenient, we could look at testing a patch on https://www.drupal.org/project/drupal/issues/2329253 and re-running the migration.

If not, all good I think?

**Comment by cbrody** [comment]
Hi @finnlewis and @DavidIIED this looks good, thanks. The migration now needs to be run against a copy of the live (i.e. stage/test) database, as this is the environment that is being updated. We'll need a stage site freeze, as well as confirmation from @mattjobob that we won't lose any modifications to news / media release items that may have been updated on stage after the original migration. Perhaps it's best to wait until I'm back on 28 September?

**Comment by finnlewis** [comment]
Just discussing with @cbrody 

Noting that this needs to be repeated on the staging site.

We'll assign it to @cbrody and assess how best to proceed. 

Happy to help.

**Comment by cbrody** [comment]
Abandoning the migration for now following unsuccessful attempts.

Need new D7 view to show News stories and press releases with related themes.

**Comment by cbrody** [comment]
See News Themes and Press release Themes tabs n https://docs.google.com/spreadsheets/d/18BP4VQSlkh6KVbRybrqoJmBZ3q6TA41kzjOALGYsOJs/edit#gid=659193577

**Comment by mattjobob** [comment]
Have commissioned freelancer to do this manually, but he's not available until early w/c 3 October. I'll do a few so the most recent content is in place, but otherwise moving this to backlog to be completed post-launch.

**Comment by mattjobob** [comment]
This is now completed
