### ISSUE TITLE
Content: Product codes not auto-generating

### ISSUE THREAD

**Issue by DavidIIED** [IIED-org/IIED-main#426]
Product codes for new pubs not being automatically generated when node edit form is saved. e.g. https://iied-main-stage.ac.iied.org/node/77936

**Comment by cbrody** [comment]
Looks like the relevant code was inadvertently commented out

**Comment by cbrody** [comment]
Fixed in #431

**Comment by mattjobob** [comment]
I've uploaded a new pub to test this: https://iied-main-stage.ac.iied.org/21121

It automatically produced a product code 21126, so it did produce a product code as per this issue, but not the one wanted. Have amended the URL, but not sure how to amend the product code? @ncktrnr @cbrody

**Comment by cbrody** [comment]
@mattjobob you can scroll to the bottom and add the desired product code in the legacy product code field.

**Comment by mattjobob** [comment]
Who knew?! Great. Thanks. All done then

**Comment by cbrody** [comment]
Not sure if it's fixed - /21126iied for some reason goes to "Establishing a Biocultural Heritage Territory to protect Kenya's Kaya forests - project launch workshop report"

**Comment by cbrody** [comment]
@mattjobob Let me know if you're not able to fix...

**Comment by mattjobob** [comment]
Ok. Now I think this is done! https://iied-main-stage.ac.iied.org/21121iied

**Comment by cbrody** [comment]
There's an issue with the second pub on the main pubs page "Establishing a Biocultural Heritage Territory..." (https://iied-main-stage.ac.iied.org/21126iied) as the URL doesn't match the product code

**Comment by mattjobob** [comment]
Thanks Chris. Have fixed both those now.
