### ISSUE TITLE
Profile page showing error 500 (Saleemul Huq)

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#429]
https://iied-main-stage.ac.iied.org/people/saleemul-huq
https://iied-main-stage.ac.iied.org/taxonomy/term/23611/edit

**Comment by cbrody** [comment]
Possible issue with name module?

**Comment by cbrody** [comment]
Possible culprit in docroot/themes/custom/iied_tw/templates/node/card/node--publication--card-md.html.twig
Line 26:   {{ node.field_media[0].entity|view('card_cover') }}

**Comment by cbrody** [comment]
media_pdf_thumbnail & name modules updated in #432

**Comment by finnlewis** [comment]
Hi @cbrody 

This is a funny one but I have found the source of the problem while not quite understanding why the problem occurs.

This publication has probs: 
http://iied-main-stage.ac.iied.org/node/64276/edit

Locally, if I remove the author Saleemul Huq and re-add, it all works again.

While removing the author, 

1. The "Publishers" field requires a value.
2. Drupal flags up that two of the other authors do not exist as taxonomy terms 

Not sure how you want to address those two, but once you do it seems to work again.

I've not edited the publication on http://iied-main-stage.ac.iied.org/node/64276/edit - I'll leave that to you.

Hope this helps.

Cheers,

Finnb

**Comment by cbrody** [comment]
Thanks @finnlewis! All fixed now.
