### ISSUE TITLE
Publication cover images issue

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#437]
Review changes to publication covers. Cards no longer working 

Temp fix to view pages node--publication--card.html.twig comments out images

e.g. /collection/urbanisation-rural-urban-linkages

Publication pages not showing e.g. https://iied-main.lndo.site/17703iied

**Comment by cbrody** [comment]
Just looking at this - there was a minor update to the media_pdf_thumbnail module yesterday which might have caused the issue.

**Comment by cbrody** [comment]
Fixed in #440

**Comment by cbrody** [comment]
Still an issue: /node/72021/edit

**Comment by cbrody** [comment]
Now actually fixed in #446
