### ISSUE TITLE
field_media empty but Download button still appears on Pubs nodes

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#469]
Found some records where there is no PDF file attachment but where there is an entity reference in the publications node field_media e.g.

https://iied-main-stage.ac.iied.org/8013iied

PDF here to re-add https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=bbfca5665f2bc14ac5a9f14ee478b45dc136e23d 
Note Don't seem to be the same one.

https://iied-main-stage.ac.iied.org/7003iied

- [x] Found at https://journals.sagepub.com/doi/epdf/10.1177/095624789000200201 

PDF could be removed and linked to on Sage as per other E&U

- [x] https://iied-main-stage.ac.iied.org/5060iied 

This is an X record with PDF on routledge.com. We can recode or more simply just delete the broken PDF

This makes the Download button appear on the node, so we'll need to either change the logic in the twig or remove the entity reference.

**Comment by ncktrnr** [comment]
Some notes added above on where to find the and re-add the PDFs, or delete in the last case. I'll update the records if that all seems OK?

**Comment by mattjobob** [comment]
@DavidIIED @cbrody Are we OK for Nick to do this? Seems OK to me.
