### ISSUE TITLE
Admin UI - Adding new Authors

### ISSUE THREAD

**Issue by DavidIIED** [IIED-org/IIED-main#471]
@cbrody & @ncktrnr ,Publication Authors are created differently on the new site (as 'People'). This now presents pubs Editors with an very long form to complete, with various irrelevant sections that must be ignored. Is there any way to simplify this or hide the sections they don't need (and shouldn't have access to) based on permissions?

**Comment by ncktrnr** [comment]
Looks fine to me, shall we close?
