### ISSUE TITLE
Fix: pubs load more feature on project pages

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#473]
Is the load more pubs button on project pages working properly, eg https://www.iied.org/empowering-producers-commercial-agriculture-epic

Page refreshes and shows one more pub - this seems right in trerms of there is one more pub to display (not sure of this) but is this not a paginated outcome rather than a load more outcome?

**Comment by cbrody** [comment]
The view should probably be using AJAX and not require a full page reload.

**Comment by mattjobob** [comment]
Resolved
