### ISSUE TITLE
Fix: news and insight page missing content between views

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#475]
There seems to be missing content between the top and bottom views on the News and Insight page: https://www.iied.org/news-and-insight

The last date of the last card in the top grid is 5 October. Yet the first card on the bottom grid starts at 28 June - meaning we are missing July-Oct?

Bottom view needs same filter as top but missing 8

**Comment by mattjobob** [comment]
This is fixed for the news and insigfht page, thanks.

However, the same issue can be seen on the news page: https://www.iied.org/news. Big gap from 13 Dec (in top grid) to 15 Aug (in bottom grid)

**Comment by ncktrnr** [comment]
The news page https://www.iied.org/news top view is set to show any nodes of type = news. The bottom half was the same with a filter to only show news type = news, not news type = press release. I've removed this second filter. There's now no missing content between top and bottom. Bottom half does now mostly contain press releases, so if needed we could consider ways to prioritise news over press releases such as a different style of card.

**Comment by mattjobob** [comment]
Dopn't think we need to prioritise, so closing
