### ISSUE TITLE
Search not working post upgrade

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#486]
- [x] Raise issue with Acquia

**Comment by cbrody** [comment]
Reverted search_api_solr #487.

**Comment by finnlewis** [comment]
I've got something working... with a patch I created on Drupal.org. Just wrapping it up a bit and will post an update. 

Basically, looks like something was missed in the latest release of search_api_solr.

**Comment by cbrody** [comment]
Thanks @finnlewis! This resolves the issue for now, at least until the next release of search_api_solr.

**Comment by finnlewis** [comment]
Re-opening this as we are discussing the patch and approach on https://www.drupal.org/project/search_api_solr/issues/3326515

@cbrody would like to progress the search_api_solr patch and get it committed on drupal.org if possible. 

The maintainer also suggests this is a problem with the data model, trying to boost on a multivalued field, which it would be to get your comments on @cbrody on the [Drupal.org issue](https://www.drupal.org/project/search_api_solr/issues/3326515)!

**Comment by cbrody** [comment]
Patches to [search_api](https://www.drupal.org/project/search_api/issues/3340305) and [search_api_solr](https://www.drupal.org/project/search_api_solr/issues/3326515) committed and credit granted to Finn for the latter.
