### ISSUE TITLE
Look at purge_file for when PDFs are replaced

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#530]
- [ ] Look at https://www.drupal.org/project/purge_file for when PDFs are replaced

_Originally posted by @cbrody in https://github.com/IIED-org/IIED-main/issues/274#issuecomment-1280661797_

**Comment by cbrody** [comment]
See PR #552

**Comment by cbrody** [comment]
TTL is currently set to 1 day during testing - change to 1 year when happy with cache-purging processes. @mattjobob can you monitor whether content changes are visible to anonymous users more or less immediately after updates?

**Comment by mattjobob** [comment]
Have been checking this over recent weeks and have noticed nothing but prompt updating. Going to close this for now
