### ISSUE TITLE
Investigate social metadata

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#566]
- [x] so page title (rather than IIED) appears when linked on social media/investigate options
- [x]  re pubs abstract pages, with a view in particular to images appearing when linked on social media

**Comment by cbrody** [comment]
This is now working I believe, but subject to cache invalidation - can you test @mattjobob ?

**Comment by mattjobob** [comment]
Excellent work @cbrody! Have tested re page title and all good, thanks. Much improved!
