### ISSUE TITLE
Deleting publications process

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#569]
All 5 of the below have been wrongly uploaded (as externals) and need deleting (no need to be in Pubs Library at all):  
 
https://www.iied.org/es/21336x
https://www.iied.org/es/21351x
https://www.iied.org/es/21346x
https://www.iied.org/es/21341x
https://www.iied.org/es/21331x
 
Can the links be reused etc?

Also need to consider how to delete the cover images and pubs files in the system

**Comment by cbrody** [comment]
Prerequisites:
- file_delete module installed
- Permissions for file_delete and media_pdf_thumbnail assigned to Manager role

Deletion process will be something like:

1. Log in as a Manager
2. Edit the publication node
3. Copy title of attached media document entity (Upload PDF)
4. Go to [/admin/content/media-grid](https://www.iied.org/admin/content/media-grid) and search for pdf title in Documents
6. Click on delete (X), copy media ID from URL but don't confirm yet
7. Go to [/admin/media-pdf-thumbnail/settings/list](https://www.iied.org/admin/media-pdf-thumbnail/settings/list)
8. Referenced Entity id  = copied media ID, click Apply
9. Scroll right on table and click Delete, then confirm
10. Go back to edit Document, confirm deletion
11. Go to [/admin/content/files](https://www.iied.org/admin/content/files)
12. Search for and delete the attached PDF file
13. Delete the pubs node

The links (publication IDs) can't be reused as they are sequentially generated by the system.

**Comment by cbrody** [comment]
Revised process with media_file_delete:

1. Log in as a Manager
2. Edit the publication node
3. Copy title of attached media document entity (Upload PDF field)
4. Click **Delete** (but don't confirm yet)
5. In a new tab go to `/admin/content/media-grid` and search for the copied title in Documents
6. Click on delete (**X**) and select "Also delete the associated file", copy the media ID from the URL (but don't confirm yet)
7. In another tab goto `/admin/media-pdf-thumbnail/settings/list`
8. Paste copied media ID into `Referenced Entity id`, click **Apply**
9. Scroll right on table and click **Delete**, then confirm
10. Go back to media item, confirm deletion
11. Go back and confirm deletion of the pubs node

**Comment by cbrody** [comment]
This is ready to test on [stage](https://iied-main-stage.ac.iied.org) prior to deploying to production and documenting. @DavidIIED @mattjobob @georginadi @ncktrnr any volunteers? Please use process as described in the most recent comment above (https://github.com/IIED-org/IIED-main/issues/569#issuecomment-1404175446).

**Comment by mattjobob** [comment]
I have checked this and - after an initial hiccup! - all looks good!

**Comment by mattjobob** [comment]
Have also logged in as other users to check access to admin pages is denied so only managers are able to cary this out

**Comment by cbrody** [comment]
The specified publications and their associated files have been deleted. @DavidIIED would you be able to update the Manager documentation with the process in https://github.com/IIED-org/IIED-main/issues/569#issuecomment-1404175446 above?
