### ISSUE TITLE
Publications Library content type change (minor)

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#572]
On Publications Library, change content type 'toolkits' plural to 'toolkit' singular

**Comment by cbrody** [comment]
I believe this is just a matter of removing the 's' from the [Toolkits taxonomy term](https://www.iied.org/taxonomy/term/67/edit) on the production site. Unless I'm missing something @ncktrnr ?

**Comment by mattjobob** [comment]
Yes, that's right

**Comment by cbrody** [comment]
That's done then!
