### ISSUE TITLE
Add copyright info to site

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#573]
On main site, add copyright IIED 2023 note to bottom left of all pages

**Comment by ncktrnr** [comment]
Text: 
© 2023 International Institute for Environment and Development (IIED)

Is this OK, or should we also add something about content on this site is licensed under a Creative Commons Attribution?

**Comment by ncktrnr** [comment]
Added as © <current year> International Institute for Environment and Development (IIED). With minor fixes for mobile accessibility

**Comment by mattjobob** [comment]
How about "Design © International Institute for Environment and Development (IIED)" to make clear it doesn't relate to the content?

**Comment by ncktrnr** [comment]
Not sure about design ©... because it also implies ownership of text, images, source code and more.  
Shall we say © 2023 IIED. Content under CC BY-NC-ND 4.0
https://www.iied.org/website-terms-conditions has the longer form, but hard to distill into a clear line.

**Comment by mattjobob** [comment]
Agreed © International Institute for Environment and Development (IIED). Can amend later if needs be
