### ISSUE TITLE
Fix: Updates section not appearing on some project pages

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#575]
'Updates section' (which show latest news, blogs, events etc connected to a project) on project pages aren't appearing on some pages.

Example where working: https://www.iied.org/advancing-understanding-disaster-displacement-ethiopia-horn-africa

Example where not working: https://www.iied.org/engaging-citizens-for-socially-just-climate-action despite https://www.iied.org/building-women-led-community-climate-movement being correctly linked to project

This afects other pages as well. can we check how many pages affected?

**Comment by ncktrnr** [comment]
Articles were excluded from related content. Have updated so that Article, Blog, Event, Long read and News can all appear on projects under Latest news and updates. Note that Events were also previously excluded.
