### ISSUE TITLE
Using solr locally

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#579]
Using solr locally for testing, including connecting to a specific solr core on acquia when running lando. Currently when running locally the production server index is used (AGHX-142716.prod.irforum), with the error:

`Acquia Search detected deprecated config settings. Please review README.txt and update 'override_search_core' setting to override.`

Snippet from settings.local.php:

```
$settings['acquia_search']['override_search_core'] = 'AGHX-142716.test.irforum';
```

**Comment by finnlewis** [comment]
I could not get `$settings['acquia_search']['override_search_core']` to work.

I went with this in my settings.local.php:

```

$config['search_api.server.acquia_search_server'] = [
  'backend_config' => [
    'connector' => 'standard',
    'connector_config' => [
      'host' => 'solr',
      'path' => '/',
      'core' => 'lando',
      'port' => '8983',
    ]
  ],
];
```

Which seems to work with the lando solr config already present.

I still see the message about 'deprecated config settings' so maybe we now need to update the solr config for the local solr core.

![image](https://user-images.githubusercontent.com/326588/215849849-63546c33-db76-43b4-9c95-03cb33299524.png)

**Comment by finnlewis** [comment]
Here's a wee pull request that allows you to see you solr admin locally: 
https://github.com/IIED-org/IIED-main/pull/583

**Comment by finnlewis** [comment]
Hey @cbrody 

Could you give me access to the solr cores settings in Acquia Cloud? 

I'm interested in how we can override the actual acquia search config, set by acquia connector, to point our local search server at the dev instance.

![image](https://user-images.githubusercontent.com/326588/215997651-805dccb6-1dbb-462e-b30c-c92c0b9c44bf.png)

**Comment by cbrody** [comment]
Hi @finnlewis you should have access now.

**Comment by finnlewis** [comment]
Thanks @cbrody !

**Comment by cbrody** [comment]
This seems to be resolved, thanks @finnlewis!
