### ISSUE TITLE
Fix: Project page not appearing

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#582]
This project page isn't appearing even though it _is_ there: www.iied.org/china-africa-forest-governance-project

Instead it redirects to this search result: https://www.iied.org/search?k=people%20international%20fellows

Can access the project page via https://www.iied.org/node/661/edit

**Comment by ncktrnr** [comment]
That's odd. There was a 301 redirect from /node/661 to  /people/international-fellows, which I've now deleted and it works. Not sure how it got there.

**Comment by mattjobob** [comment]
Thanks Nick - in hindsight I should have checked the redirects
