### ISSUE TITLE
Multiple pages returning server errors

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#648]
Pages returning "Temporarily Unavailable" error on Acquia (log shows `PHP Fatal error: Aborting! The New Relic imposed maximum PHP function nesting level of '5000' has been reached...`, and opening these links in a local copy of the site results in out of memory issues.)

Themes
https://iied.org/policy-planning
https://iied.org/poverty

Collections
https://iied.org/collection/stepping-global-ambition-for-climate-action-justice

Publications
https://www.iied.org/g04133
https://iied.org/17604iied
https://iied.org/g04170
https://iied.org/x00215
https://iied.org/G04161
https://iied.org/G04162
https://iied.org/G04137
https://iied.org/17590IIED
https://iied.org/17354IIED
https://iied.org/17576IIED
https://iied.org/G03814
https://iied.org/G03810

...all relating to the below project

Project
https://iied.org/building-capacity-for-pro-poor-responses-wildlife-crime-uganda

... and publication 
https://iied.org/21171iied 

relating to project https://www.iied.org/transparency-programme-supporting-ldcs-negotiate-implement-enhanced-transparency-framework-under 

The issue would seem to be with some embedded publication block views. https://www.drupal.org/project/drupal/issues/2979184 may be related.

Also could be connected to recently installed link checker module, where publications content existent links to authors and PDFs. Link checker is presently uninstalled.

The fix involved unlinking all the publications from broken project pages until finding the nodes causing the issue:
https://iied.org/21171iied and (most likely) https://iied.org/x00215

**Comment by ncktrnr** [comment]
Issue fixed for now. All pages working again. More detailed comment to follow

**Comment by ncktrnr** [comment]
I've updated the list of affected pages above. Problem resolved albeit without clearly identifying the root cause. It looks like there were two publications causing issues where they were linked up the chain, i.e projects, collections, themes. In both cases the PDFs where missing, so recommendations for now are to avoid linking any publications without PDFs to projects, for example X records.
