### ISSUE TITLE
Pubs issues (missing download buttons)

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#674]
Something strange going on with this pub - https://www.iied.org/zh-hans/17651CIIED
It's available via https://www.iied.org/sites/default/files/pdfs/migrate/17651CIIED.pdf but doesn't download when you click on the download button. Any others like this?

Now fixed along with 38 others. Mostly Chinese language not imported properly on migration. For most of them the corresponding media entry needed updating. In cases where translated versions were added as standalone titles the original versions have been updated. Some URLs have changed as below.

From | to |  
-- | -- | --
https://www.iied.org/zh-hans/13558CIIED | https://www.iied.org/zh-hans/13558iied |  
https://www.iied.org/es/13558SIIED | https://www.iied.org/es/13558iied |  
https://www.iied.org/fr/13558FIIED | https://www.iied.org/fr/13558iied |  
https://www.iied.org/zh-hans/13558CIIED | https://www.iied.org/zh-hans/13558iied |  
https://iied.org/zh-hans/g03794 | https://iied.org/zh-hans/g03759 | Translation added
https://iied.org/zh-hans/g04107 | https://iied.org/zh-hans/g04101 | Translation added
https://iied.org/zh-hans/g04028 | https://iied.org/zh-hans/17579iied | Translation added
https://iied.org/zh-hans/g03957 | https://iied.org/zh-hans/g03944 | Translation added
https://iied.org/zh-hans/g03960 | https://iied.org/zh-hans/g03946 | Translation added
https://iied.org/zh-hans/g03959 | https://iied.org/zh-hans/g03945 | Translation added
https://iied.org/zh-hans/g03958 | https://iied.org/zh-hans/g03947 | Translation added

**Comment by ncktrnr** [comment]
I'll add redirects just to be thorough.
