### ISSUE TITLE
Minor updates/fixes (July 2023)

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#681]
- [x] Not possible to add “community-based adaptation” tag (eg on [IIED Europe event page](https://www.iied.org/forging-climate-resilient-europe-learning-community-based-adaptation-practitioners-outside-europe)). Because of number of CBA events, “community-based adaptation” never comes up
- [x] Remove additional/duplicated  'research group' that appears in the contact section on project pages (MW)
- [x] Update style of headings on Highcharts/tables to be more prominent. At moment, using heading 4 (eg at bottom of https://www.iied.org/we-need-new-layered-approach-debt-relief-climate-financing) but then heading isnlt connected to chart (Can use the chart title field, but text is centred)
- [x] Add ability to add multiple staff contacts to project pages, so project appears on their staff profile (but project pages retain only one person as main contact) (MW - have we done this?)
- [x] Add ability to have non-displayed images on theme and collection pages - and add images to each
- [x] Fix pubs Sort by relevance styling
- [x] id="download" appears in the banner buttons (e.g. annual report) where it shouldn't 
- [x] remove research group from project contact
- [x] add node created date to /admin/content view

**Comment by ncktrnr** [comment]
RE: not possible to add CBA tag on IIED Europe event page. It's difficult to change the number of suggestions in the dropdown. Since it's not a common problem the get around is to paste in the full tag name and ID: 'Community-Based Adaptation (CBA) (1056)'

**Comment by ncktrnr** [comment]
RE: Remove additional/duplicated 'research group'. The display for contact is made up of Full name + Position + Research group. Looks like Position in some cases includes the research group e.g. https://www.iied.org/people/helen-oconnor, where normally it's more like this example https://www.iied.org/people/florence-crick. 

Can we change the person page to include the group name so it doesn't need adding in the position? Otherwise we can remove Research group from the project contact, so only Position is displayed.

**Comment by mattjobob** [comment]
Thanks Nick. Re CBA - what's the easiest way to find out/know the full tag name and ID? Eg, go into the edit screen of another page using the tag?

**Comment by mattjobob** [comment]
RE: Remove additional/duplicated 'research group': I think better to remove the research group from the project contact. 

Given groups are on the way out supposedly, the potential introduction of task teams, and how we already know some research stuff (legal tools) team find it more useful to have their team than research group listed, I think this greater flexibility is the better answer for now.

The Flo example shows how this doesn't work on project pages either: eg https://www.iied.org/climate-change-conflict-reframing-debate

**Comment by mattjobob** [comment]
Completed!
