### ISSUE TITLE
Error fixes

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#745]
Errors multiple_registration.module etc. 

Warning: foreach() argument must be of type array|object, null given in /app/docroot/modules/contrib/config_devel/src/EventSubscriber/ConfigDevelAutoImportSubscriber.php on line 18

Warning: Undefined array key 0 in /app/docroot/modules/contrib/multiple_registration/multiple_registration.module on line 391

Warning: Trying to access array offset on value of type null in /app/docroot/modules/contrib/multiple_registration/multiple_registration.module on line 391

Error message
Close
Warning: foreach() argument must be of type array|object, null given in Drupal\config_devel\EventSubscriber\ConfigDevelAutoImportSubscriber->autoImportConfig() (line 18 of modules/contrib/config_devel/src/EventSubscriber/ConfigDevelAutoImportSubscriber.php).
Drupal\config_devel\EventSubscriber\ConfigDevelAutoImportSubscriber->autoImportConfig(Object, 'kernel.request', Object)
call_user_func(Array, Object, 'kernel.request', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.request') (Line: 145)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

- [x] Uninstalled uninstalled: config_devel

**Comment by cbrody** [comment]
Removed config_devel from Local config split in #747
