### ISSUE TITLE
Header/navigation updates

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/IIED-main#860]
Improvements to do 

- [ ] Spacing on secondary menu search page 
- [ ] Change focus on search and publications page to existing search bar 
- [ ] Off canvas menu themes add extra margin bottom
- [ ] Search box, smooth open/close. Open can look a little jerky. Investigate possible conflict on certain pages (e.g. home)

**Comment by ncktrnr** [comment]
Updates to new branch https://github.com/IIED-org/IIED-main/tree/feature/860-header-updates-20240828

- logo too big for mobile, recreate in 2 parts: logo and logotype, logotype is hidden for mobile.
- add x-cloak to avoid 'flash' of responsive menu before page load 
- update button pseudo states 
- update scroll-nav.js to refactor code. Function is now all in separate file 
- update scroll-nav.js to improve scroll function 
- update off-canvas menu style, spacing and padding
- update off-canvas menu function, now transitions from top
- update off-canvas menu to use drupal menus and remove static links 
- update page.html.twig, remove JS, add twig blocks 
- extend other layout twig where copies of page.html.twig (except page--search which just gets new header)

**Comment by cbrody** [comment]
Testing doc: https://iied.sharepoint.com/:w:/s/WebTeam/EZjlH7zwfFlCuYWCWe_jx_sBoaO-D-3o2UIF2uirvx9FGg?e=Yhtm9c

**Comment by ncktrnr** [comment]
Fixes done
- [x] rearrange social icons
- [x] order themes list vertically on larger screens. This is a technical challenge, but agree it would be easier to scan
- [x] add newsletter icon 
- [x] fix spacing at bottom of theme list. This was due to the offset from top of page that I'm not sure is necessary
- [x] test scroll position options, if we can on improve
- [x] test mobile arrows
- [x] adjust spacing: bigger margin for larger screens 
- [x] HP banner fix spacing on buttons: need to fit on same line
- [x] browser /device tests
