### ISSUE TITLE
Migrate IIED main site

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#899]
www.iied.org
https://prod.iied.org

- [ ] Make test plan
- [x] Test prod site
- [x] Feature freeze
- [x] Merge and deploy #895 
- [x] Content freeze - readonlymode?
- [x] Migrate db & files
- [x] Test
- [x] Update DNS etc.
- [x] Test

Launch target: 20241015T11:00

**Comment by stephen-cox** [comment]
@cbrody This site is now ready to test on the new server at: https://prod.iied.org/

I'm off next week so can look at any issues you fine then.
