### ISSUE TITLE
Add & configure cloudflare purger

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#912]
Pages and pdfs not being updated for logged-in or anonymous users

- [x] Add module
- [ ] Configure & test
- [ ] Deploy

**Comment by cbrody** [comment]
Hi @stephen-cox the module is in the feature branch linked to this issue

**Comment by stephen-cox** [comment]
Hi @cbrody, I have been looking at this module, but can't get it to do what we need.

I have found that Cloudflare is not caching HTML content, so changes to pages are cached by Varnish until the purge queue worker is run, which happens every 5 minutes and is also run when Drupal cron runs.

Cloudflare is caching PDFs though. I have tried to configure the Cloudflare purger module, but I get an error when it tries to clear the CF cache about cache tags only being supported by the enterprise service. It seems the module will automatically try to clear cache tags when the Core Tags Queuer module is enabled and we can't disable this as it's needed by Varnish Purge.

As I have a better understanding of the issue now I'll have to think about the best way forward with this.

**Comment by stephen-cox** [comment]
Hi @cbrody, I've had another look at this and reached the conclusion that it's not possible to selectively clear the Cloudflare cache with our current set up.

Drupal's caching is heavily built around cache tags, but Cloudflare only supports cache tags in it's enterprise service. The integration with the Purge module only really works with cache tags and so it can't be used.

There is a [Cloudflare Purge](https://www.drupal.org/project/cloudflare_purge) module, but this invalidates the Cloudflare cache for an entire zone. To test this out, I have installed this on the stage site. You should be able to clear the Cloudflare cache here: https://stage.iied.org/admin/config/cloudflare-purge. A word of warning, it does this for all iied.org URLs and sub domains.

If PDFs are updated regularly and need to be fresh, my suggestion is to exclude them from the Cloudflare cache. If it doesn't matter if they're a little stale then we could set a rule only cache PDFs for an hour or two.

We can also include the Cloudflare Purge which would give managers or editors the ability to nuke the Cloudflare cache if something needs to be visible straight away.

How does that sound to you?

**Comment by cbrody** [comment]
Thanks @stephen-cox for your work on this. Closing for now, as the issue isn't critical and we have a way of manually clearing the CF cache. I'll document the process and share if useful.

**Comment by cbrody** [comment]
Cloudflare cache TTL set to "Respect existing headers"
