### ISSUE TITLE
Old publications causing server errors

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#915]
`The website encountered an unexpected error. Try again later.`

Originally found with https://www.iied.org/7004iied it seems that other old E&U pubs are causing problems with search results pages, as well as when opening the publication page itself. For example (via https://www.iied.org/search?k=environmentandurbanization):

https://www.iied.org/10552iied
https://www.iied.org/9542iied
https://www.iied.org/9001iied

https://www.iied.org/5060iied
https://www.iied.org/5008iied

There are likely to be more. The old (FoR) pubs site is temporarily available at the following URL, if we decide to re-create the affected pubs, e.g. as "X" records:

https://ec2-35-176-204-129.eu-west-2.compute.amazonaws.com

- [x] Further investigation / debugging
- [ ] Fix
- [ ] See also https://github.com/IIED-org/IIED-main/issues/736

**Comment by ncktrnr** [comment]
Thanks Chris, this ought to be enough to narrow it down and get a list to delete/recreate. Looks like they're all E&U that (probably) have data in the PDF field that shouldn't be there. For info you can get to the revisions, for example 
https://www.iied.org/node/38131/revisions/77176/view
https://www.iied.org/node/44376/revisions/77261/view
Reverting to old versions doesn't help though.

**Comment by cbrody** [comment]
media_pdf_thumbnail was erroring at line 237 of docroot/modules/contrib/media_pdf_thumbnail/src/Plugin/Field/FieldFormatter/MediaPdfThumbnailImageFieldFormatter.php. Adding a test for null value (if statement around lines 216 to 283) seems to fix it temporarily, while we look at patching or replacing the module.

**Comment by ncktrnr** [comment]
Fix looks good. 
As a side issue we might want to suppress citations from appearing on X records where publications isn't available anyway e.g. http://dev.iied.org/5008iied

**Comment by cbrody** [comment]
Thanks Nick! I guess if we do show the citation it should link to the DOI, yes?
